name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'public-stable-ids.txt'
      - 'settings.gradle'
  workflow_dispatch:

jobs:
  build:
    name: Build release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Eclipse Temurin JDK 21.0.6
        uses: actions/setup-java@v4
        with:
          java-version: '21.0.6'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build release apk
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: app/build/outputs/apk/release
